#!/usr/bin/env python
"""strip outputs from an IPython Notebook
Opens a notebook, strips its output, and writes the outputless version to the original file.
Useful mainly as a git pre-commit hook for users who don't want to track output in VCS.
This does mostly the same thing as the `Clear All Output` command in the notebook UI.
Adapted from rom https://gist.github.com/minrk/6176788 to work with
git filter driver
"""
import sys

from IPython.nbformat import current 

def strip_output(nb):
    """strip the outputs from a notebook object"""
    for ws in nb.worksheets:
        for cell in ws.cells:
            if 'outputs' in cell:
                cell['outputs'] = []
            if 'prompt_number' in cell:
                del cell['prompt_number']
    return nb

if __name__ == '__main__':
    nb = current.reads(sys.stdin.read(), 'json')
    nb = strip_output(nb)
    sys.stdout.write(current.writes(nb, 'json'))

